# Site settings
title: Shree Consultants
description: "Income Tax and PF Consultants"
url: "http://www.auditorbhr.github.io/emerald"
author:
  name: "Murali Bhat"
  email: "shrcoff@gmail.com"
  url: "http://www.auditorbhr.github.io/emerald/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: :title
paginate: 8
paginate_path: page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
